//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.8.0
//
// Created by Quasar Development at 15-10-2015
//
//---------------------------------------------------


#import "FGAHelper.h"
#import "FGAappContent.h"


@implementation FGAappContent
@synthesize author;
@synthesize channelId;
@synthesize contentId;
@synthesize description;
@synthesize releaseDate;
@synthesize shortTitle;
@synthesize title;
@synthesize txt;

+ (FGAappContent *)createWithXml:(DDXMLElement *)__node __request:(FGARequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(FGARequestResultHandler*) __request{
    if(self = [self init])
    {
        if([FGAHelper hasValue:__node name:@"author" index:0])
        {
            self.author = [[FGAHelper getNode:__node name:@"author" index:0] stringValue];
        }
        if([FGAHelper hasValue:__node name:@"channelId" index:0])
        {
            self.channelId = [NSNumber numberWithInt:[[[FGAHelper getNode:__node name:@"channelId" index:0] stringValue] intValue]];
        }
        if([FGAHelper hasValue:__node name:@"contentId" index:0])
        {
            self.contentId = [NSNumber numberWithInt:[[[FGAHelper getNode:__node name:@"contentId" index:0] stringValue] intValue]];
        }
        if([FGAHelper hasValue:__node name:@"description" index:0])
        {
            self.description = [[FGAHelper getNode:__node name:@"description" index:0] stringValue];
        }
        if([FGAHelper hasValue:__node name:@"releaseDate" index:0])
        {
            self.releaseDate = [FGAHelper getDate:[[FGAHelper getNode:__node name:@"releaseDate" index:0] stringValue]];
        }
        if([FGAHelper hasValue:__node name:@"shortTitle" index:0])
        {
            self.shortTitle = [[FGAHelper getNode:__node name:@"shortTitle" index:0] stringValue];
        }
        if([FGAHelper hasValue:__node name:@"title" index:0])
        {
            self.title = [[FGAHelper getNode:__node name:@"title" index:0] stringValue];
        }
        if([FGAHelper hasValue:__node name:@"txt" index:0])
        {
            self.txt = [[FGAHelper getNode:__node name:@"txt" index:0] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(FGARequestResultHandler*) __request
{

             
    DDXMLElement* __authorItemElement=[__request writeElement:author type:[NSString class] name:@"author" URI:@"" parent:__parent skipNullProperty:YES];
    if(__authorItemElement!=nil)
    {
        [__authorItemElement setStringValue:self.author];
    }
             
    DDXMLElement* __channelIdItemElement=[__request writeElement:channelId type:[NSNumber class] name:@"channelId" URI:@"" parent:__parent skipNullProperty:YES];
    if(__channelIdItemElement!=nil)
    {
        [__channelIdItemElement setStringValue:[self.channelId stringValue]];
    }
             
    DDXMLElement* __contentIdItemElement=[__request writeElement:contentId type:[NSNumber class] name:@"contentId" URI:@"" parent:__parent skipNullProperty:YES];
    if(__contentIdItemElement!=nil)
    {
        [__contentIdItemElement setStringValue:[self.contentId stringValue]];
    }
             
    DDXMLElement* __descriptionItemElement=[__request writeElement:description type:[NSString class] name:@"description" URI:@"" parent:__parent skipNullProperty:YES];
    if(__descriptionItemElement!=nil)
    {
        [__descriptionItemElement setStringValue:self.description];
    }
             
    DDXMLElement* __releaseDateItemElement=[__request writeElement:releaseDate type:[NSDate class] name:@"releaseDate" URI:@"" parent:__parent skipNullProperty:YES];
    if(__releaseDateItemElement!=nil)
    {
        [__releaseDateItemElement setStringValue:[FGAHelper getStringFromDateTime:self.releaseDate]];
    }
             
    DDXMLElement* __shortTitleItemElement=[__request writeElement:shortTitle type:[NSString class] name:@"shortTitle" URI:@"" parent:__parent skipNullProperty:YES];
    if(__shortTitleItemElement!=nil)
    {
        [__shortTitleItemElement setStringValue:self.shortTitle];
    }
             
    DDXMLElement* __titleItemElement=[__request writeElement:title type:[NSString class] name:@"title" URI:@"" parent:__parent skipNullProperty:YES];
    if(__titleItemElement!=nil)
    {
        [__titleItemElement setStringValue:self.title];
    }
             
    DDXMLElement* __txtItemElement=[__request writeElement:txt type:[NSString class] name:@"txt" URI:@"" parent:__parent skipNullProperty:YES];
    if(__txtItemElement!=nil)
    {
        [__txtItemElement setStringValue:self.txt];
    }


}
@end
