//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.8.0
//
// Created by Quasar Development at 15-10-2015
//
//---------------------------------------------------



#import <Foundation/Foundation.h>

#import "FGAappContentArray.h"
#import "FGAappContent.h"
#import "DDXML.h"

@class FGARequestResultHandler;

@protocol FGASoapServiceResponse < NSObject>
- (void) onSuccess: (id) value methodName:(NSString*)methodName;
- (void) onError: (NSError*) error;
@end


@interface FGAAppChannelWebSvcServiceSoapBinding : NSObject
    
@property (retain, nonatomic) NSDictionary* Headers;
@property (retain, nonatomic) NSString* Url;
@property (nonatomic) BOOL ShouldAddAdornments;
@property BOOL EnableLogging;

- (id) init;
- (id) initWithUrl: (NSString*) url;

-(NSMutableURLRequest*) creategetAppContentListRequest:(NSNumber*) channelId __request:(FGARequestResultHandler*) __request;
-(FGAappContentArray*) getAppContentList:(NSNumber*) channelId __error:(NSError**) __error;
-(FGARequestResultHandler*) getAppContentListAsync:(NSNumber*) channelId __target:(id) __target __handler:(SEL) __handler;
-(FGARequestResultHandler*) getAppContentListAsync:(NSNumber*) channelId __target:(id<FGASoapServiceResponse>) __target;
-(FGARequestResultHandler*) getAppContentListAsyncWithBlock:(NSNumber*) channelId __handler:(void(^) (id)) __handler;
-(NSMutableURLRequest*) creategetAppContentRequest:(NSNumber*) contentId __request:(FGARequestResultHandler*) __request;
-(FGAappContent*) getAppContent:(NSNumber*) contentId __error:(NSError**) __error;
-(FGARequestResultHandler*) getAppContentAsync:(NSNumber*) contentId __target:(id) __target __handler:(SEL) __handler;
-(FGARequestResultHandler*) getAppContentAsync:(NSNumber*) contentId __target:(id<FGASoapServiceResponse>) __target;
-(FGARequestResultHandler*) getAppContentAsyncWithBlock:(NSNumber*) contentId __handler:(void(^) (id)) __handler;
-(NSString*) getAppChannelList:(NSString*) channelId __error:(NSError**) __error;
-(FGARequestResultHandler*) getAppChannelListAsync:(NSString*) channelId __target:(id) __target __handler:(SEL) __handler;
-(FGARequestResultHandler*) getAppChannelListAsync:(NSString*) channelId __target:(id<FGASoapServiceResponse>) __target;
-(FGARequestResultHandler*) getAppChannelListAsyncWithBlock:(NSString*) channelId __handler:(void(^) (id)) __handler;
-(FGARequestResultHandler*) CreateRequestResultHandler;   
-(NSMutableURLRequest*) createRequest :(NSString*) soapAction __request:(FGARequestResultHandler*) __request; 
-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(FGARequestResultHandler*) requestMgr; 
-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(FGARequestResultHandler*) requestMgr callback:(void (^)(FGARequestResultHandler *)) callback;

@end
