//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.8.0
//
// Created by Quasar Development at 15-10-2015
//
//---------------------------------------------------


#import "FGAAppChannelWebSvcServiceSoapBinding.h"
#import "FGARequestResultHandler.h"
#import "FGAHelper.h"

@implementation FGAAppChannelWebSvcServiceSoapBinding
@synthesize Url,ShouldAddAdornments,Headers;
@synthesize EnableLogging;

- (id) init {
    if(self = [super init])
    {
        self.Url=@"http://172.16.10.86:8080/jeecms/webService/getAppChannelList";
        self.ShouldAddAdornments=YES;
    }
    return self;
}

- (id) initWithUrl: (NSString*) url {
    if(self = [self init])
    {
        self.Url=url;
    }
    return self;
}

-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(FGARequestResultHandler*) requestMgr
{
    [requestMgr sendImplementation:request];
}

-(FGARequestResultHandler*) CreateRequestResultHandler
{
    FGARequestResultHandler* handler= [[FGARequestResultHandler alloc]init:SOAPVERSION_11];
    handler.EnableLogging = EnableLogging;
    return handler;
}

-(NSMutableURLRequest*) createRequest:(NSString *)__soapAction __request:(FGARequestResultHandler*) __request
{
    NSURL *__url = [NSURL URLWithString:Url];
    NSMutableURLRequest *__requestObj = [NSMutableURLRequest requestWithURL:__url];
    [__request prepareRequest:__requestObj];

    [__requestObj addValue: [NSString stringWithFormat:@"\"%@\"", __soapAction] forHTTPHeaderField:@"SOAPAction"];

    for (NSString* key in self.Headers) {
        [__requestObj addValue: [self.Headers objectForKey:key] forHTTPHeaderField:key];
    }
    [__requestObj setHTTPMethod:@"POST"];

    return __requestObj;
}


-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(FGARequestResultHandler*) requestMgr callback:(void (^)(FGARequestResultHandler *)) callback
{
    [requestMgr sendImplementation:request callbackDelegate:callback];
}

-(void) addAdornments:(DDXMLElement*)__methodElement
{
    if(ShouldAddAdornments)
    {
        [__methodElement addAttribute:[DDXMLNode attributeWithName:@"id" stringValue:@"o0"]];
        [__methodElement addAttribute:[DDXMLNode attributeWithName:@"c:root" stringValue:@"1"]];
    }
}

-(NSMutableURLRequest*) creategetAppContentListRequest:(NSNumber*) channelId __request:(FGARequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"getAppContentList" URI:@"http://webservice.app.com/" parent:__request.Body];
    [self addAdornments:__methodElement];
             
    DDXMLElement* __channelIdItemElement=[__request writeElement:channelId type:[NSNumber class] name:@"channelId" URI:@"" parent:__methodElement skipNullProperty:NO];
    if(__channelIdItemElement!=nil)
    {
        [__channelIdItemElement setStringValue:[channelId stringValue]];
    }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@""  __request:__request];
    return __requestObj;
    }
    
-(FGARequestResultHandler*) getAppContentListAsync:(NSNumber*) channelId __target:(id) __target __handler:(SEL) __handler
{
    FGARequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self creategetAppContentListRequest:channelId __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(FGARequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[FGAHelper getResultElement:__request.OutputBody name:@"return"];
        __res= (FGAappContentArray*)[__request createObject:__result type:[FGAappContentArray class]];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    IMP imp = [__target methodForSelector:__handler];
    void (*func)(id, SEL,id) = (void *)imp;
    func(__target, __handler,__res);
    }];
    return __request;
}

-(FGARequestResultHandler*) getAppContentListAsync:(NSNumber*) channelId __target:(id<FGASoapServiceResponse>) __target
{
    FGARequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self creategetAppContentListRequest:channelId __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(FGARequestResultHandler *__requestMgr) {
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[FGAHelper getResultElement:__request.OutputBody name:@"return"];
        [__target onSuccess:(FGAappContentArray*)[__request createObject:__result type:[FGAappContentArray class]] methodName:@"getAppContentList"];
    }
    else
    {
        [__target onError:__requestMgr.OutputFault];
    }
    }];
    return __request;
}
-(FGARequestResultHandler*) getAppContentListAsyncWithBlock:(NSNumber*) channelId __handler:(void(^) (id)) __handler
{
    FGARequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self creategetAppContentListRequest:channelId __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(FGARequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[FGAHelper getResultElement:__request.OutputBody name:@"return"];
        __res= (FGAappContentArray*)[__request createObject:__result type:[FGAappContentArray class]];
    }
    else
    {
    __res=__requestMgr.OutputFault;
    }
    
    __handler(__res);
    }];
    return __request;
    }

-(FGAappContentArray*) getAppContentList:(NSNumber*) channelId __error:(NSError**) __error
{
    FGARequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self creategetAppContentListRequest:channelId __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[FGAHelper getResultElement:__request.OutputBody name:@"return"];
    return (FGAappContentArray*)[__request createObject:__result type:[FGAappContentArray class]];
}
-(NSMutableURLRequest*) creategetAppContentRequest:(NSNumber*) contentId __request:(FGARequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"getAppContent" URI:@"http://webservice.app.com/" parent:__request.Body];
    [self addAdornments:__methodElement];
             
    DDXMLElement* __contentIdItemElement=[__request writeElement:contentId type:[NSNumber class] name:@"contentId" URI:@"" parent:__methodElement skipNullProperty:NO];
    if(__contentIdItemElement!=nil)
    {
        [__contentIdItemElement setStringValue:[contentId stringValue]];
    }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@""  __request:__request];
    return __requestObj;
    }
    
-(FGARequestResultHandler*) getAppContentAsync:(NSNumber*) contentId __target:(id) __target __handler:(SEL) __handler
{
    FGARequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self creategetAppContentRequest:contentId __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(FGARequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[FGAHelper getResultElement:__request.OutputBody name:@"return"];
        __res= (FGAappContent*)[__request createObject:__result type:[FGAappContent class]];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    IMP imp = [__target methodForSelector:__handler];
    void (*func)(id, SEL,id) = (void *)imp;
    func(__target, __handler,__res);
    }];
    return __request;
}

-(FGARequestResultHandler*) getAppContentAsync:(NSNumber*) contentId __target:(id<FGASoapServiceResponse>) __target
{
    FGARequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self creategetAppContentRequest:contentId __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(FGARequestResultHandler *__requestMgr) {
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[FGAHelper getResultElement:__request.OutputBody name:@"return"];
        [__target onSuccess:(FGAappContent*)[__request createObject:__result type:[FGAappContent class]] methodName:@"getAppContent"];
    }
    else
    {
        [__target onError:__requestMgr.OutputFault];
    }
    }];
    return __request;
}
-(FGARequestResultHandler*) getAppContentAsyncWithBlock:(NSNumber*) contentId __handler:(void(^) (id)) __handler
{
    FGARequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self creategetAppContentRequest:contentId __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(FGARequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[FGAHelper getResultElement:__request.OutputBody name:@"return"];
        __res= (FGAappContent*)[__request createObject:__result type:[FGAappContent class]];
    }
    else
    {
    __res=__requestMgr.OutputFault;
    }
    
    __handler(__res);
    }];
    return __request;
    }

-(FGAappContent*) getAppContent:(NSNumber*) contentId __error:(NSError**) __error
{
    FGARequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self creategetAppContentRequest:contentId __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[FGAHelper getResultElement:__request.OutputBody name:@"return"];
    return (FGAappContent*)[__request createObject:__result type:[FGAappContent class]];
}
    
-(FGARequestResultHandler*) getAppChannelListAsync:(NSString*) channelId __target:(id) __target __handler:(SEL) __handler
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

-(FGARequestResultHandler*) getAppChannelListAsync:(NSString*) channelId __target:(id<FGASoapServiceResponse>) __target
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}
-(FGARequestResultHandler*) getAppChannelListAsyncWithBlock:(NSString*) channelId __handler:(void(^) (id)) __handler
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
    }

-(NSString*) getAppChannelList:(NSString*) channelId __error:(NSError**) __error
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

@end
